### ISSUE TITLE
gremlin python subgraph

### ISSUE THREAD

**Issue by Espade** [krlawrence/graph#190] opened 2020-06-18 07:36 UTC
Hi, thank you for your repo, which helps me a lot.

I have one question though: everytime when I run ```subGraph = self.g.V().has(*vertex).repeat(__.inE().subgraph('subGraph').outV()).times(3).cap('subGraph').next()```, it returns an empty result. Why is that?

**Comment by krlawrence** [comment] 2020-06-19 15:07
What is *vertex in your query? This test works fine for me:

```
t=g.V().has('code','AUS').repeat(__.inE().subgraph('subGraph').outV()).times(2).cap('subGraph').next()

**Comment by Espade** [comment] 2020-06-22 07:42
My vertex is same as yours.

But mine query always returns empty result. I searched for gremlin python for this problem, and people say `subgraph` is not well supported in gremlin python.

**Comment by krlawrence** [comment] 2020-06-22 13:20
It works fine for me in Gremlin Python
```
>>> t=g.V().has('code','AUS').repeat(__.inE().subgraph('subGraph').outV()).times(2).cap('subGraph').next()
>>> type(t)
<class 'dict'>
>>> t.keys()
dict_keys(['@type', '@value'])
>>> t['@value'].keys()
dict_keys(['vertices', 'edges'])
>>> t['@value']['vertices'][:4]
[v[2793], v[1220], v[1217], v[1216]]
>>> t['@value']['edges'][:4]
[e[43576][1050-route->180], e[43573][1050-route->9], e[4970][40-route->16], e[43574][1050-route->30]]
>>>
```

**Comment by Espade** [comment] 2020-06-24 08:01
I have tried your code, still empty.
What is your gremlin server configuration?

**Comment by krlawrence** [comment] 2020-06-24 13:04
I was connected to Amazon Neptune when I did my tests. I can try with a Gremlin Server also.

**Comment by krlawrence** [comment] 2020-07-03 00:43
As I cannot reproduce what you are seeing I am going to close this for now. Feel free to re-open if you come up with a way to reproduce consistently.

**Closed by krlawrence** 2020-07-03 00:43 UTC
Labels: question
